# Generated by Django 4.2 on 2023-06-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btb1', '0002_rd_desc_rd_space_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(default=0)),
                ('phone', models.IntegerField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='rd',
            name='desc',
            field=models.CharField(default='Add description', max_length=255),
        ),
        migrations.AlterField(
            model_name='rd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btb1.user1'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
