# Generated by Django 4.2 on 2023-06-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btb1', '0003_user1_alter_rd_desc_alter_rd_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rd',
            old_name='build_name',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='desc',
            new_name='comments',
        ),
    ]
