# Generated by Django 4.2 on 2023-06-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btb1', '0004_rename_build_name_rd_building_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
