# Generated by Django 4.2 on 2023-06-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btb1', '0005_alter_user1_phone_alter_user1_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='btb1.user1'),
        ),
    ]
