# Generated by Django 4.2 on 2023-06-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btb1', '0007_alter_rd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btb1.user1'),
        ),
    ]
