# Generated by Django 4.2 on 2023-06-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btb1', '0008_alter_rd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
