# Generated by Django 4.2 on 2023-06-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btb1', '0009_alter_user1_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd',
            name='user',
        ),
    ]
