# Generated by Django 4.2 on 2023-06-23 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btb1', '0011_alter_user1_username_delete_rd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
